### ISSUE TITLE
Investigate ways to communicate with Google Calendar API

### ISSUE THREAD

**Issue by nandanmen** [ubclaunchpad/when3meet#11]
Ideally we would want to synchronize the data in the user's Google Calendar with Firebase, so that the availabilities will live update when events are added/removed.

**Comment by jamesmengo** [comment]
https://developers.google.com/calendar/quickstart/go

@kx-chen @jackyzha0 @gokcedilek 

I've created a branch following this article, but I'm still quite unfamiliar with golang best practices so:
1) How you guys would like to structure this (create a subfolder for clients?)
2) Are there any packages that are unnecessary that have been added?

We can either discuss here or I can open an empty PR for a Request for Comments

**Comment by jamesmengo** [comment]
https://github.com/ubclaunchpad/when3meet/pull/15

Note that credentials.json has been stored in Google Drive

How to use

1) run: `go run clients/quickstart.go` from the directory
2) Follow the link in the console which opens up the oAuth flow
3) Click accept until you're redirected to Google. (This was just used as a test redirect URL). The token should be part of the URL (we can work on improving this of course, there's stuff before and after the token that you don't want to include)
4) Enter the token into terminal
5) Token.json will be saved

**Comment by jackyzha0** [comment]
folders in Go create submodules, so if we do go down this route, the folder could be renamed to `gcal` and it would ideally be a module we can reuse in the main logic of our backend

**Comment by jackyzha0** [comment]
Go cleans up unused deps so you shouldn't need to worry about it!

**Comment by jamesmengo** [comment]
> folders in Go create submodules, so if we do go down this route, the folder could be renamed to `gcal` and it would ideally be a module we can reuse in the main logic of our backend

What are the other options here?

**Comment by bobheadxi** [comment]
> Note that credentials.json has been stored in Google Drive

I would recommend putting this somewhere not in the Projects drive (which has very liberal access), and also you should _immediately_ invalidate and regenerate your key, since it is still available in Git history: https://github.com/ubclaunchpad/when3meet/pull/15/commits/c0e7c4ccc6607c20a6dfc09b45624197b5d89432

Why we don't put secrets in Drive: https://docs.ubclaunchpad.com/handbook/tools/drive

**Comment by jackyzha0** [comment]
> > folders in Go create submodules, so if we do go down this route, the folder could be renamed to `gcal` and it would ideally be a module we can reuse in the main logic of our backend
> 
> What are the other options here?

Honestly this is probably the most idiomatic way to do it in Go and probably cleanest way to go about it

If we kept GCal logic spread throughout our code, that's a lot of coupling

**Comment by nandanmen** [comment]
@bobheadxi Any recommendations where we should put these vulnerable files?

**Comment by nandanmen** [comment]
> #15
> 
> Note that credentials.json has been stored in Google Drive
> 
> How to use
> 
>     1. run: `go run clients/quickstart.go` from the directory
> 
>     2. Follow the link in the console which opens up the oAuth flow
> 
>     3. Click accept until you're redirected to Google. (This was just used as a test redirect URL). The token should be part of the URL (we can work on improving this of course, there's stuff before and after the token that you don't want to include)
> 
>     4. Enter the token into terminal
> 
>     5. Token.json will be saved

Can you add this to the PR description? Would be easier to access for reviewers.

**Comment by bobheadxi** [comment]
> Any recommendations where we should put these vulnerable files?

Unfortunately not at the moment 😞  https://github.com/ubclaunchpad/rocket2/issues/557 (@SarahBornais) is an idea, but that won't be available for a while. I would recommend that this file _not_ be shared at all:

* For development, each person should have their own integration set up (to avoid messing up each others' setups)
* For deployment, only one person needs to manage the integration

If you really want to share it, I would keep it on someone's personal drive and just share the specific file only
