### ISSUE TITLE
Vue3 instead of Vue2

### ISSUE THREAD

**Issue by tnwin** [ubclaunchpad/when3meet#17]
I noticed our project is setup in Vue2. I think Vue3 has more support for TypeScript and it'd be good to familiar ourselves with what will soon become the standard. @narendrasss also linked us the Vue3 docs too. What do y'all think?

**Comment by nandanmen** [comment]
Thanks for bringing this up! I had a chat with @francismacapobre earlier today and I think we decided to upgrade to Vue 3. I'm working on doing this migration tonight.
