### ISSUE TITLE
Implement event endpoints

### ISSUE THREAD

**Issue by nandanmen** [ubclaunchpad/when3meet#24]
# Task 🔨

Create the endpoints necessary to create, update, read, and delete events. 

- For now let's only support creating an event with _specific dates_ instead of any day of the week.
- Remember to conform to the event schema that we defined last week. Here it is again:

```
{
	users: string[] // user ids
	owners: string[]
	scheduleWindow: {
		startTime: string // date string in ISO8601
		endTime: string
	}
	link: string
	calendar: Calendar
}
```

And the calendar:

```
{
	blocks: [
	  {
		startTime: string // date string in ISO8601
		availableUsers: string[] // user ids
	  }
	]
}
```

# Related MVP Tasks ⚙️ 

### Create

- [Set title](https://www.notion.so/when3meet-5dce74ed4f8e4ec3b79c13de7eb2e8f7?p=f2380af4f65f461ca54eeac00756cf5c)
- [Set description](https://www.notion.so/when3meet-5dce74ed4f8e4ec3b79c13de7eb2e8f7?p=1b15a39fc92748c58aa5ea183f31645e)
- [Set specific date(s) and time(s)](https://www.notion.so/when3meet-5dce74ed4f8e4ec3b79c13de7eb2e8f7?p=7cdb0ab18a37411da5fd430166317f72)

### Update

- [Select availability](https://www.notion.so/when3meet-5dce74ed4f8e4ec3b79c13de7eb2e8f7?p=42878ccf3a1a42f89880af0a6218eb34)

# Related Wireframes ✏️ 

N/A

# Related Issues ⚠️ 

#21

**Comment by jamesmengo** [comment]
@narendrasss We have CRUD endpoints to update an event. Do we want specific endpoints to set these fields individually or could we just send an updated event object over?

**Comment by nandanmen** [comment]
> @narendrasss We have CRUD endpoints to update an event. Do we want specific endpoints to set these fields individually or could we just send an updated event object over?

@jmengo Sending an updated event object should be fine
