### ISSUE TITLE
Setup firebase and connect to REST API

### ISSUE THREAD

**Issue by nandanmen** [ubclaunchpad/when3meet#3]
- [ ] Setup firebase
- [ ] Connect instance to REST API (maybe have the API retrieve and send back some dummy data or something)

**Comment by jackyzha0** [comment]
Should we set up a personal Firebase project or is there a club Firebase we can use

**Comment by nandanmen** [comment]
cc @bobheadxi - is there a club google account we can use here?

**Comment by bobheadxi** [comment]
There is, but we don't have an official policy for how to use it yet. For simpler access, I would recommend you use a personal account for now and keep a migration path to the official account if the project graduates to a "official" Launch Pad project (another process I think might be a good threshold for when to use the main Launch Pad account - added a task to write something up in https://github.com/ubclaunchpad/docs/issues/196)

Using a new personal account also means you get free tiers / trials :)
